spring.application.name=mingle_market

# Supabase 연결
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.waytazrxehyjdpnwadoq
spring.datasource.password=dajungmingle12@!
spring.datasource.driver-class-name=org.postgresql.Driver

# Mybatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.mingle_market.dto
mybatis.configuration.map-underscore-to-camel-case=true